# =============================================================
# SonarQube - Configuración del proyecto AppReservas
# =============================================================

sonar.projectKey=taller_app_reservas
sonar.projectName=taller_app_reservas
sonar.projectVersion=1.0

# Carpetas con código fuente a analizar
sonar.sources=auth-service,booking-service,frontend,notification-service,user-service

sonar.sourceEncoding=UTF-8

# Excluir archivos que no deben afectar el Quality Gate
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.scannerwork/**,**/*.spec.js,**/*.test.js,**/*.spec.ts,**/*.test.ts,**/tools/**
